### ISSUE TITLE
Merging everything to main AwesomeTTS repository?

### ISSUE THREAD

**Issue by woj-tek** [lovac42/awesometts-CCBC-addon#8]
Given that AwesomeTTS got some life recently (see: https://github.com/AwesomeTTS/awesometts-anki-addon/issues/69#issuecomment-644741256) maybe you could consider:
* merging all you changes there
* becoming contributor/member of AwesomeTTS

So in the end we would only have one plugin?

**Comment by luc-vocab** [comment]
I'd be more than happy to help with some of the merging ! Especially when testing services, I'm a strong believer in automated testing, and we now have a framework in place in awesometts to make sure TTS output is correct.

**Comment by luc-vocab** [comment]
Is this repository currently being published on an AnkiWeb addon page ? If so, which one ?

**Comment by lovac42** [comment]
I don't think @krassowski would like it if you merge this into the main branch. As he previously stated:
> However, I need to say that I feel uncomfortable with some of the proposed
changes ...

This is not published on ankiweb and mostly works for CCBC, my own fork of anki 2.0.

**Comment by krassowski** [comment]
I am not contributing code fixes to AwesomeTTS any longer (and I am not the author of the extension either) so my opinion might be of little relevance now, but as I was mentioned here, I will just clarify that I did not like _certain proposals_ which tried to implement/fix services _by reverse engineering_ clients rather than using the dedicated and fully legal APIs. Which paths you will take from here is your own choice - anyways I think that Anki with TTS support was/is/will be an excellent and very useful thing and it is worth consolidating the efforts to bring it back and improve.

**Comment by luc-vocab** [comment]
Noted, it's true that scraping/reverse engineering APIs causes problems and breaks often. However some users are very attached to those services. I don't see it practical to remove them. As far as awesome-CCBC-addon goes, i'm flexible on the approach. If people want to contribute code, i'll help out, but repositories can continue to exist separately. Also, i'm proposing something in #9

**Comment by lovac42** [comment]
In that case, feel free to cherry pick the changes as I had taken them from other forks.

Separating the services as krassowski had previously suggested would be in the right direction. Also, put a limit/timer on these online services so they don't hammer the server. I'm afraid I can't spend too much time on this, otherwise I'd have taken over maintenance of ATTS.

**Comment by luc-vocab** [comment]
OK sounds good, thank you, I will do that.
